@startuml

abstract Automaton {
- String name;
- HashSet<String> Q;
- HashSet<Character>  Sigma;
- HashMap<S, D> delta;
- String q0;
- HashSet<String> F;

+ Automaton(StateSet Q);

+ {abstract} boolean isAccept(String inputString);
+ String convert2Tape();
+ String toString();

}

Automaton <|-- DFA
class DFA {
+ boolean isAccept(String inputString);
}

Automaton <|-- NFA
class NFA {
- HashSet<String> acceptEpsilonCharacter(HashSet<String> currentStateSet);
+ DFA convert2DFA();
+ boolean isAccept(String inputString);
}

NFA <|-- PDA
class PDA {
+ HashSet<String> Gamma;
- HashSet<Pair> acceptEpsilonCharacter(HashSet<Pair> currentStateSet);
+ boolean isAccept(String inputString);
}

PDAState --- PDA

class PDAState {
- String stateName;
- Deque<Character> stack;

+ PDAState(stateName);
+ Triple tripenize(Character ch);
+ PDAState updatePDAState(Pair pair);
}

Automaton <-- TuringMaschine

class TuringMaschine{
- String name;
- HashSet<String> Q;
- HashSet<String> Sigma;
- HashSet<String> Gamma;
- HashMap<Pair<String, String>, Triplet<String, String, Character>> delta;
- String q0;
- Sttring qAccept;
- String qReject;

+ TuringMaschine(StateSet Q, Alphabet Sigma, Tape Gamma, HashMap delta, State q0, State qAccept, State qReject);
+ void reset();
+ void loadProgram(String program);
+ boolean isAccept(String inputTape);
}

class Pair {
}

class Triple {
}

@enduml